### ISSUE TITLE
CA问题～

### ISSUE THREAD

**Issue by novioleo** [recall704/Husky#1]
大佬你好，问个问题：
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "checksum": "1c3e56363a98fd4a091b1c96d222cd0c46a8c33b", "msg": "Destination directory /home/novio/tmp_store/kubernetes/Husky/src/roles/2-ca/output/ca does not exist"}
在进行task2的时候告诉我没有这个ca文件，这个东西用什么生成的呀。？

**Comment by novioleo** [comment]
i found it in template.sorry to bother.

**Comment by recall704** [comment]
是本地没有这个文件夹，你创建一下就好了

**Comment by novioleo** [comment]
i noticed that.thks.
